In [284]:
from librerias import *

In [285]:
ruta_archivo = 'Data/btc_limp.csv' 

btc = pd.read_csv(ruta_archivo)
btc.set_index('Date', inplace=True)

In [286]:

# Asegúrate de que el índice de tu DataFrame sea de tipo datetime
btc.index = pd.to_datetime(btc.index)

# Utiliza la función resample con la frecuencia 'MS' para obtener el primer día de cada mes
btc_mes = btc.resample('MS').first()

# Elimina los datos anteriores a '2014-01-01'
btc_mes = btc_mes.loc['2014-01-01':]

In [287]:
btc_mes = btc_mes ['Open']
btc_mes = pd.DataFrame (btc_mes)

In [288]:
btc_sin_up = btc_mes.copy ()
btc_sin_up = pd.DataFrame (btc_sin_up)
btc_sin_up.index = pd.to_datetime(btc_sin_up.index)

btc_down = btc_mes.copy ()
btc_down = pd.DataFrame (btc_down)
btc_down.index = pd.to_datetime(btc_down.index)

btc_sin_up_down = btc_mes.copy ()
btc_sin_up_down = pd.DataFrame (btc_sin_up_down)
btc_sin_up_down.index = pd.to_datetime(btc_sin_up_down.index)

btc_sin_up

             Open
Date
2014-01-01    805
2014-02-01    938
2014-03-01    573
2014-04-01    444
2014-05-01    445
2014-06-01    627
2014-07-01    635
2014-08-01    589
2014-09-01    481
2014-10-01    388
2014-11-01    337
2014-12-01    374
2015-01-01    318
2015-02-01    218
2015-03-01    254
2015-04-01    244
2015-05-01    235
2015-06-01    229
2015-07-01    264
2015-08-01    283
2015-09-01    229
2015-10-01    235
2015-11-01    311
2015-12-01    378
2016-01-01    430
2016-02-01    369
2016-03-01    436
2016-04-01    415
2016-05-01    448
2016-06-01    528
2016-07-01    670
2016-08-01    621
2016-09-01    573
2016-10-01    608
2016-11-01    698
2016-12-01    742
2017-01-01    963
2017-02-01    965
2017-03-01   1189
2017-04-01   1079
2017-05-01   1351
2017-06-01   2303
2017-07-01   2480
2017-08-01   2883
2017-09-01   4735
2017-10-01   4360
2017-11-01   6449
2017-12-01   9947
2018-01-01  13850
2018-02-01  10266
2018-03-01  10335
2018-04-01   6939
2018-05-01   9245
2018-06-01   7502
2018-07-01   6398
2018-08-01   7728
2018-09-01   7032
2018-10-01   6635
2018-11-01   6365
2018-12-01   4038
2019-01-01   3709
2019-02-01   3437
2019-03-01   3816
2019-04-01   4102
2019-05-01   5321
2019-06-01   8556
2019-07-01  10821
2019-08-01  10081
2019-09-01   9594
2019-10-01   8285
2019-11-01   9153
2019-12-01   7546
2020-01-01   7196
2020-02-01   9349
2020-03-01   8543
2020-04-01   6412
2020-05-01   8628
2020-06-01   9454
2020-07-01   9135
2020-08-01  11333
2020-09-01  11644
2020-10-01  10776
2020-11-01  13795
2020-12-01  19697
2021-01-01  28951
2021-02-01  33106
2021-03-01  45160
2021-04-01  58763
2021-05-01  57719
2021-06-01  37294
2021-07-01  35030
2021-08-01  41510
2021-09-01  47129
2021-10-01  43824
2021-11-01  61310
2021-12-01  56891
2022-01-01  46217
2022-02-01  38475
2022-03-01  43187
2022-04-01  45529
2022-05-01  37642
2022-06-01  31793
2022-07-01  19926
2022-08-01  23303
2022-09-01  20049
2022-10-01  19422
2022-11-01  20496
2022-12-01  17163
2023-01-01  16537
2023-02-01  23124
2023-03-01  23130
2023-04-01  28473
2023-05-01  29252
2023-06-01  27216
2023-07-01  30472
2023-08-01  29232
2023-09-01  25938
2023-10-01  26962
2023-11-01  34648
2023-12-01  37712
2024-01-01  42272
2024-02-01  42580
2024-03-01  61157

In [289]:
btc_mes ['retornos']= btc_mes ['Open'].pct_change ().round (2)

btc_mes ['ganancias'] = (1 + btc_mes['retornos']).cumprod()

btc_mes

             Open  retornos  ganancias
Date
2014-01-01    805       NaN        NaN
2014-02-01    938      0.17   1.170000
2014-03-01    573     -0.39   0.713700
2014-04-01    444     -0.23   0.549549
2014-05-01    445      0.00   0.549549
2014-06-01    627      0.41   0.774864
2014-07-01    635      0.01   0.782613
2014-08-01    589     -0.07   0.727830
2014-09-01    481     -0.18   0.596820
2014-10-01    388     -0.19   0.483425
2014-11-01    337     -0.13   0.420579
2014-12-01    374      0.11   0.466843
2015-01-01    318     -0.15   0.396817
2015-02-01    218     -0.31   0.273803
2015-03-01    254      0.17   0.320350
2015-04-01    244     -0.04   0.307536
2015-05-01    235     -0.04   0.295235
2015-06-01    229     -0.03   0.286378
2015-07-01    264      0.15   0.329334
2015-08-01    283      0.07   0.352388
2015-09-01    229     -0.19   0.285434
2015-10-01    235      0.03   0.293997
2015-11-01    311      0.32   0.388076
2015-12-01    378      0.22   0.473453
2016-01-01    430      0.14   0.539736
2016-02-01    369     -0.14   0.464173
2016-03-01    436      0.18   0.547724
2016-04-01    415     -0.05   0.520338
2016-05-01    448      0.08   0.561965
2016-06-01    528      0.18   0.663119
2016-07-01    670      0.27   0.842161
2016-08-01    621     -0.07   0.783210
2016-09-01    573     -0.08   0.720553
2016-10-01    608      0.06   0.763786
2016-11-01    698      0.15   0.878354
2016-12-01    742      0.06   0.931055
2017-01-01    963      0.30   1.210372
2017-02-01    965      0.00   1.210372
2017-03-01   1189      0.23   1.488757
2017-04-01   1079     -0.09   1.354769
2017-05-01   1351      0.25   1.693461
2017-06-01   2303      0.70   2.878884
2017-07-01   2480      0.08   3.109195
2017-08-01   2883      0.16   3.606666
2017-09-01   4735      0.64   5.914932
2017-10-01   4360     -0.08   5.441738
2017-11-01   6449      0.48   8.053772
2017-12-01   9947      0.54  12.402809
2018-01-01  13850      0.39  17.239904
2018-02-01  10266     -0.26  12.757529
2018-03-01  10335      0.01  12.885105
2018-04-01   6939     -0.33   8.633020
2018-05-01   9245      0.33  11.481917
2018-06-01   7502     -0.19   9.300353
2018-07-01   6398     -0.15   7.905300
2018-08-01   7728      0.21   9.565413
2018-09-01   7032     -0.09   8.704525
2018-10-01   6635     -0.06   8.182254
2018-11-01   6365     -0.04   7.854964
2018-12-01   4038     -0.37   4.948627
2019-01-01   3709     -0.08   4.552737
2019-02-01   3437     -0.07   4.234045
2019-03-01   3816      0.11   4.699790
2019-04-01   4102      0.07   5.028776
2019-05-01   5321      0.30   6.537408
2019-06-01   8556      0.61  10.525228
2019-07-01  10821      0.26  13.261787
2019-08-01  10081     -0.07  12.333462
2019-09-01   9594     -0.05  11.716789
2019-10-01   8285     -0.14  10.076438
2019-11-01   9153      0.10  11.084082
2019-12-01   7546     -0.18   9.088947
2020-01-01   7196     -0.05   8.634500
2020-02-01   9349      0.30  11.224850
2020-03-01   8543     -0.09  10.214613
2020-04-01   6412     -0.25   7.660960
2020-05-01   8628      0.35  10.342296
2020-06-01   9454      0.10  11.376526
2020-07-01   9135     -0.03  11.035230
2020-08-01  11333      0.24  13.683685
2020-09-01  11644      0.03  14.094196
2020-10-01  10776     -0.07  13.107602
2020-11-01  13795      0.28  16.777730
2020-12-01  19697      0.43  23.992155
2021-01-01  28951      0.47  35.268467
2021-02-01  33106      0.14  40.206053
2021-03-01  45160      0.36  54.680231
2021-04-01  58763      0.30  71.084301
2021-05-01  57719     -0.02  69.662615
2021-06-01  37294     -0.35  45.280700
2021-07-01  35030     -0.06  42.563858
2021-08-01  41510      0.18  50.225352
2021-09-01  47129      0.14  57.256901
2021-10-01  43824     -0.07  53.248918
2021-11-01  61310      0.40  74.548486
2021-12-01  56891     -0.07  69.330092
2022-01-01  46217     -0.19  56.157374
2022-02-01  38475     -0.17  46.610621
2022-03-01  43187      0.12  52.203895
2022-04-01  45529      0.05  54.814090
2022-05-01  37642     -0.17  45.495695
2022-06-01  31793     -0.16  38.216383
2022-07-01  19926     -0.37  24.076322
2022-08-01  23303      0.17  28.169296
2022-09-01  20049     -0.14  24.225595
2022-10-01  19422     -0.03  23.498827
2022-11-01  20496      0.06  24.908757
2022-12-01  17163     -0.16  20.923355
2023-01-01  16537     -0.04  20.086421
2023-02-01  23124      0.40  28.120990
2023-03-01  23130      0.00  28.120990
2023-04-01  28473      0.23  34.588817
2023-05-01  29252      0.03  35.626482
2023-06-01  27216     -0.07  33.132628
2023-07-01  30472      0.12  37.108544
2023-08-01  29232     -0.04  35.624202
2023-09-01  25938     -0.11  31.705540
2023-10-01  26962      0.04  32.973761
2023-11-01  34648      0.29  42.536152
2023-12-01  37712      0.09  46.364406
2024-01-01  42272      0.12  51.928134
2024-02-01  42580      0.01  52.447416
2024-03-01  61157      0.44  75.524279

In [290]:
mejores = btc_mes.loc[btc_mes['retornos'].nlargest(25).index]
peores = btc_mes.loc[btc_mes['retornos'].nsmallest(25).index]

peor = btc_mes.sort_values(by='retornos', ascending=True)[:20]

peores_retornos = btc_mes['retornos'].nsmallest(25, keep='all')



peores_retornos

Date
2014-03-01   -0.39
2018-12-01   -0.37
2022-07-01   -0.37
2021-06-01   -0.35
2018-04-01   -0.33
2015-02-01   -0.31
2018-02-01   -0.26
2020-04-01   -0.25
2014-04-01   -0.23
2014-10-01   -0.19
2015-09-01   -0.19
2018-06-01   -0.19
2022-01-01   -0.19
2014-09-01   -0.18
2019-12-01   -0.18
2022-02-01   -0.17
2022-05-01   -0.17
2022-06-01   -0.16
2022-12-01   -0.16
2015-01-01   -0.15
2018-07-01   -0.15
2016-02-01   -0.14
2019-10-01   -0.14
2022-09-01   -0.14
2014-11-01   -0.13
Name: retornos, dtype: float64

In [291]:
btc_sin_up = btc_sin_up.drop(mejores.index)
btc_sin_up ['retornos']= btc_sin_up ['Open'].pct_change ().round (2)
btc_sin_up ['ganancias'] = (1 + btc_sin_up['retornos']).cumprod().round (2)
btc_sin_up

             Open  retornos  ganancias
Date
2014-01-01    805       NaN        NaN
2014-02-01    938      0.17       1.17
2014-03-01    573     -0.39       0.71
2014-04-01    444     -0.23       0.55
2014-05-01    445      0.00       0.55
2014-07-01    635      0.43       0.79
2014-08-01    589     -0.07       0.73
2014-09-01    481     -0.18       0.60
2014-10-01    388     -0.19       0.49
2014-11-01    337     -0.13       0.42
2014-12-01    374      0.11       0.47
2015-01-01    318     -0.15       0.40
2015-02-01    218     -0.31       0.27
2015-03-01    254      0.17       0.32
2015-04-01    244     -0.04       0.31
2015-05-01    235     -0.04       0.30
2015-06-01    229     -0.03       0.29
2015-07-01    264      0.15       0.33
2015-08-01    283      0.07       0.35
2015-09-01    229     -0.19       0.29
2015-10-01    235      0.03       0.30
2015-12-01    378      0.61       0.48
2016-01-01    430      0.14       0.54
2016-02-01    369     -0.14       0.47
2016-03-01    436      0.18       0.55
2016-04-01    415     -0.05       0.52
2016-05-01    448      0.08       0.56
2016-06-01    528      0.18       0.67
2016-08-01    621      0.18       0.79
2016-09-01    573     -0.08       0.72
2016-10-01    608      0.06       0.77
2016-11-01    698      0.15       0.88
2016-12-01    742      0.06       0.93
2017-02-01    965      0.30       1.21
2017-03-01   1189      0.23       1.49
2017-04-01   1079     -0.09       1.36
2017-07-01   2480      1.30       3.13
2017-08-01   2883      0.16       3.63
2017-10-01   4360      0.51       5.47
2018-02-01  10266      1.35      12.86
2018-03-01  10335      0.01      12.99
2018-04-01   6939     -0.33       8.71
2018-06-01   7502      0.08       9.40
2018-07-01   6398     -0.15       7.99
2018-08-01   7728      0.21       9.67
2018-09-01   7032     -0.09       8.80
2018-10-01   6635     -0.06       8.27
2018-11-01   6365     -0.04       7.94
2018-12-01   4038     -0.37       5.00
2019-01-01   3709     -0.08       4.60
2019-02-01   3437     -0.07       4.28
2019-03-01   3816      0.11       4.75
2019-04-01   4102      0.07       5.08
2019-08-01  10081      1.46      12.51
2019-09-01   9594     -0.05      11.88
2019-10-01   8285     -0.14      10.22
2019-11-01   9153      0.10      11.24
2019-12-01   7546     -0.18       9.22
2020-01-01   7196     -0.05       8.75
2020-03-01   8543      0.19      10.42
2020-04-01   6412     -0.25       7.81
2020-06-01   9454      0.47      11.49
2020-07-01   9135     -0.03      11.14
2020-08-01  11333      0.24      13.82
2020-09-01  11644      0.03      14.23
2020-10-01  10776     -0.07      13.23
2021-02-01  33106      2.07      40.63
2021-05-01  57719      0.74      70.69
2021-06-01  37294     -0.35      45.95
2021-07-01  35030     -0.06      43.19
2021-08-01  41510      0.18      50.97
2021-09-01  47129      0.14      58.10
2021-10-01  43824     -0.07      54.04
2021-12-01  56891      0.30      70.25
2022-01-01  46217     -0.19      56.90
2022-02-01  38475     -0.17      47.23
2022-03-01  43187      0.12      52.89
2022-04-01  45529      0.05      55.54
2022-05-01  37642     -0.17      46.10
2022-06-01  31793     -0.16      38.72
2022-07-01  19926     -0.37      24.39
2022-08-01  23303      0.17      28.54
2022-09-01  20049     -0.14      24.55
2022-10-01  19422     -0.03      23.81
2022-11-01  20496      0.06      25.24
2022-12-01  17163     -0.16      21.20
2023-01-01  16537     -0.04      20.35
2023-03-01  23130      0.40      28.49
2023-04-01  28473      0.23      35.05
2023-05-01  29252      0.03      36.10
2023-06-01  27216     -0.07      33.57
2023-07-01  30472      0.12      37.60
2023-08-01  29232     -0.04      36.10
2023-09-01  25938     -0.11      32.13
2023-10-01  26962      0.04      33.41
2023-12-01  37712      0.40      46.77
2024-01-01  42272      0.12      52.39
2024-02-01  42580      0.01      52.91

In [292]:
btc_down = btc_down.drop(peores.index)
btc_down ['retornos']= btc_down ['Open'].pct_change ().round (2)
btc_down ['ganancias'] = (1 + btc_down['retornos']).cumprod().round (2)
btc_down

             Open  retornos  ganancias
Date
2014-01-01    805       NaN        NaN
2014-02-01    938      0.17       1.17
2014-05-01    445     -0.53       0.55
2014-06-01    627      0.41       0.78
2014-07-01    635      0.01       0.78
2014-08-01    589     -0.07       0.73
2014-12-01    374     -0.37       0.46
2015-03-01    254     -0.32       0.31
2015-04-01    244     -0.04       0.30
2015-05-01    235     -0.04       0.29
2015-06-01    229     -0.03       0.28
2015-07-01    264      0.15       0.32
2015-08-01    283      0.07       0.34
2015-10-01    235     -0.17       0.28
2015-11-01    311      0.32       0.38
2015-12-01    378      0.22       0.46
2016-01-01    430      0.14       0.52
2016-03-01    436      0.01       0.53
2016-04-01    415     -0.05       0.50
2016-05-01    448      0.08       0.54
2016-06-01    528      0.18       0.64
2016-07-01    670      0.27       0.81
2016-08-01    621     -0.07       0.76
2016-09-01    573     -0.08       0.69
2016-10-01    608      0.06       0.74
2016-11-01    698      0.15       0.85
2016-12-01    742      0.06       0.90
2017-01-01    963      0.30       1.17
2017-02-01    965      0.00       1.17
2017-03-01   1189      0.23       1.44
2017-04-01   1079     -0.09       1.31
2017-05-01   1351      0.25       1.63
2017-06-01   2303      0.70       2.78
2017-07-01   2480      0.08       3.00
2017-08-01   2883      0.16       3.48
2017-09-01   4735      0.64       5.70
2017-10-01   4360     -0.08       5.25
2017-11-01   6449      0.48       7.77
2017-12-01   9947      0.54      11.96
2018-01-01  13850      0.39      16.63
2018-03-01  10335     -0.25      12.47
2018-05-01   9245     -0.11      11.10
2018-08-01   7728     -0.16       9.32
2018-09-01   7032     -0.09       8.48
2018-10-01   6635     -0.06       7.97
2018-11-01   6365     -0.04       7.65
2019-01-01   3709     -0.42       4.44
2019-02-01   3437     -0.07       4.13
2019-03-01   3816      0.11       4.58
2019-04-01   4102      0.07       4.90
2019-05-01   5321      0.30       6.38
2019-06-01   8556      0.61      10.26
2019-07-01  10821      0.26      12.93
2019-08-01  10081     -0.07      12.03
2019-09-01   9594     -0.05      11.43
2019-11-01   9153     -0.05      10.85
2020-01-01   7196     -0.21       8.58
2020-02-01   9349      0.30      11.15
2020-03-01   8543     -0.09      10.14
2020-05-01   8628      0.01      10.25
2020-06-01   9454      0.10      11.27
2020-07-01   9135     -0.03      10.93
2020-08-01  11333      0.24      13.56
2020-09-01  11644      0.03      13.96
2020-10-01  10776     -0.07      12.99
2020-11-01  13795      0.28      16.62
2020-12-01  19697      0.43      23.77
2021-01-01  28951      0.47      34.94
2021-02-01  33106      0.14      39.83
2021-03-01  45160      0.36      54.17
2021-04-01  58763      0.30      70.42
2021-05-01  57719     -0.02      69.01
2021-07-01  35030     -0.39      42.10
2021-08-01  41510      0.18      49.68
2021-09-01  47129      0.14      56.63
2021-10-01  43824     -0.07      52.67
2021-11-01  61310      0.40      73.73
2021-12-01  56891     -0.07      68.57
2022-03-01  43187     -0.24      52.11
2022-04-01  45529      0.05      54.72
2022-08-01  23303     -0.49      27.91
2022-10-01  19422     -0.17      23.16
2022-11-01  20496      0.06      24.55
2023-01-01  16537     -0.19      19.89
2023-02-01  23124      0.40      27.84
2023-03-01  23130      0.00      27.84
2023-04-01  28473      0.23      34.25
2023-05-01  29252      0.03      35.27
2023-06-01  27216     -0.07      32.81
2023-07-01  30472      0.12      36.74
2023-08-01  29232     -0.04      35.27
2023-09-01  25938     -0.11      31.39
2023-10-01  26962      0.04      32.65
2023-11-01  34648      0.29      42.12
2023-12-01  37712      0.09      45.91
2024-01-01  42272      0.12      51.42
2024-02-01  42580      0.01      51.93
2024-03-01  61157      0.44      74.78

In [293]:
btc_sin_up_down = btc_sin_up_down.drop(peores.index).dropna ()
btc_sin_up_down = btc_sin_up_down.drop (mejores.index).dropna ()
btc_sin_up_down ['retornos']= btc_sin_up_down ['Open'].pct_change ().round (2)
btc_sin_up_down ['ganancias'] = (1 + btc_sin_up_down['retornos']).cumprod().round (2)
btc_sin_up_down.dropna ()

             Open  retornos  ganancias
Date
2014-02-01    938      0.17       1.17
2014-05-01    445     -0.53       0.55
2014-07-01    635      0.43       0.79
2014-08-01    589     -0.07       0.73
2014-12-01    374     -0.37       0.46
2015-03-01    254     -0.32       0.31
2015-04-01    244     -0.04       0.30
2015-05-01    235     -0.04       0.29
2015-06-01    229     -0.03       0.28
2015-07-01    264      0.15       0.32
2015-08-01    283      0.07       0.34
2015-10-01    235     -0.17       0.29
2015-12-01    378      0.61       0.46
2016-01-01    430      0.14       0.52
2016-03-01    436      0.01       0.53
2016-04-01    415     -0.05       0.50
2016-05-01    448      0.08       0.54
2016-06-01    528      0.18       0.64
2016-08-01    621      0.18       0.76
2016-09-01    573     -0.08       0.70
2016-10-01    608      0.06       0.74
2016-11-01    698      0.15       0.85
2016-12-01    742      0.06       0.90
2017-02-01    965      0.30       1.17
2017-03-01   1189      0.23       1.44
2017-04-01   1079     -0.09       1.31
2017-07-01   2480      1.30       3.01
2017-08-01   2883      0.16       3.50
2017-10-01   4360      0.51       5.28
2018-03-01  10335      1.37      12.51
2018-08-01   7728     -0.25       9.38
2018-09-01   7032     -0.09       8.54
2018-10-01   6635     -0.06       8.03
2018-11-01   6365     -0.04       7.71
2019-01-01   3709     -0.42       4.47
2019-02-01   3437     -0.07       4.16
2019-03-01   3816      0.11       4.61
2019-04-01   4102      0.07       4.94
2019-08-01  10081      1.46      12.14
2019-09-01   9594     -0.05      11.54
2019-11-01   9153     -0.05      10.96
2020-01-01   7196     -0.21       8.66
2020-03-01   8543      0.19      10.30
2020-06-01   9454      0.11      11.44
2020-07-01   9135     -0.03      11.09
2020-08-01  11333      0.24      13.76
2020-09-01  11644      0.03      14.17
2020-10-01  10776     -0.07      13.18
2021-02-01  33106      2.07      40.45
2021-05-01  57719      0.74      70.39
2021-07-01  35030     -0.39      42.94
2021-08-01  41510      0.18      50.66
2021-09-01  47129      0.14      57.76
2021-10-01  43824     -0.07      53.71
2021-12-01  56891      0.30      69.83
2022-03-01  43187     -0.24      53.07
2022-04-01  45529      0.05      55.72
2022-08-01  23303     -0.49      28.42
2022-10-01  19422     -0.17      23.59
2022-11-01  20496      0.06      25.00
2023-01-01  16537     -0.19      20.25
2023-03-01  23130      0.40      28.35
2023-04-01  28473      0.23      34.87
2023-05-01  29252      0.03      35.92
2023-06-01  27216     -0.07      33.41
2023-07-01  30472      0.12      37.41
2023-08-01  29232     -0.04      35.92
2023-09-01  25938     -0.11      31.97
2023-10-01  26962      0.04      33.25
2023-12-01  37712      0.40      46.54
2024-01-01  42272      0.12      52.13
2024-02-01  42580      0.01      52.65

In [294]:
import dash
from dash import dcc, html
import plotly.graph_objs as go

# Crear la aplicación Dash
app = dash.Dash(__name__)

# Definir los datos
data = [
    {'x': btc_sin_up_down.index, 'y': btc_sin_up_down['ganancias'], 'name': 'btc_sin_up_down', 'line': {'color': 'blue', 'dash': 'solid'}},
    {'x': btc_down.index, 'y': btc_down['ganancias'], 'name': 'btc_down', 'line': {'color': 'red', 'dash': 'dash'}},
    {'x': btc_sin_up.index, 'y': btc_sin_up['ganancias'], 'name': 'btc_sin_up', 'line': {'color': 'green', 'dash': 'dot'}},
    {'x': btc_mes.index, 'y': btc_mes['ganancias'], 'name': 'btc_mes', 'line': {'color': 'orange', 'dash': 'dashdot'}}
]

# Crear el layout de la aplicación Dash
app.layout = html.Div([
    dcc.Graph(
        id='graph',
        figure={
            'data': data,
            'layout': {
                'title': 'Ganancias de Bitcoin',
                'xaxis': {'title': 'Fecha'},
                'yaxis': {'title': 'Ganancias'},
                'legend': {'orientation': 'h'}
            }
        }
    )
])

# Ejecutar la aplicación
if __name__ == '__main__':
    app.run_server(debug=True)

OSError: Address 'http://127.0.0.1:8050' already in use.
    Try passing a different port to run_server.

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Muestra el DataFrame completo
print(btc_down)

             Open  retornos  ganancias
Date
2014-01-01    805       NaN        NaN
2014-02-01    938      0.17       1.17
2014-05-01    445     -0.53       0.55
2014-06-01    627      0.41       0.78
2014-07-01    635      0.01       0.78
2014-08-01    589     -0.07       0.73
2014-12-01    374     -0.37       0.46
2015-03-01    254     -0.32       0.31
2015-04-01    244     -0.04       0.30
2015-05-01    235     -0.04       0.29
2015-06-01    229     -0.03       0.28
2015-07-01    264      0.15       0.32
2015-08-01    283      0.07       0.34
2015-10-01    235     -0.17       0.28
2015-11-01    311      0.32       0.38
2015-12-01    378      0.22       0.46
2016-01-01    430      0.14       0.52
2016-03-01    436      0.01       0.53
2016-04-01    415     -0.05       0.50
2016-05-01    448      0.08       0.54
2016-06-01    528      0.18       0.64
2016-07-01    670      0.27       0.81
2016-08-01    621     -0.07       0.76
2016-09-01    573     -0.08       0.69
2016-10-01    608      0.06       0.74
2016-11-01    698      0.15       0.85
2016-12-01    742      0.06       0.90
2017-01-01    963      0.30       1.17
2017-02-01    965      0.00       1.17
2017-03-01   1189      0.23       1.44
2017-04-01   1079     -0.09       1.31
2017-05-01   1351      0.25       1.63
2017-06-01   2303      0.70       2.78
2017-07-01   2480      0.08       3.00
2017-08-01   2883      0.16       3.48
2017-09-01   4735      0.64       5.70
2017-10-01   4360     -0.08       5.25
2017-11-01   6449      0.48       7.77
2017-12-01   9947      0.54      11.96
2018-01-01  13850      0.39      16.63
2018-03-01  10335     -0.25      12.47
2018-05-01   9245     -0.11      11.10
2018-08-01   7728     -0.16       9.32
2018-09-01   7032     -0.09       8.48
2018-10-01   6635     -0.06       7.97
2018-11-01   6365     -0.04       7.65
2019-01-01   3709     -0.42       4.44
2019-02-01   3437     -0.07       4.13
2019-03-01   3816      0.11       4.58
2019-04-01   4102      0.07       4.90
2019-05-01   5321      0.30       6.38
2019-06-01   8556      0.61      10.26
2019-07-01  10821      0.26      12.93
2019-08-01  10081     -0.07      12.03
2019-09-01   9594     -0.05      11.43
2019-11-01   9153     -0.05      10.85
2020-01-01   7196     -0.21       8.58
2020-02-01   9349      0.30      11.15
2020-03-01   8543     -0.09      10.14
2020-05-01   8628      0.01      10.25
2020-06-01   9454      0.10      11.27
2020-07-01   9135     -0.03      10.93
2020-08-01  11333      0.24      13.56
2020-09-01  11644      0.03      13.96
2020-10-01  10776     -0.07      12.99
2020-11-01  13795      0.28      16.62
2020-12-01  19697      0.43      23.77
2021-01-01  28951      0.47      34.94
2021-02-01  33106      0.14      39.83
2021-03-01  45160      0.36      54.17
2021-04-01  58763      0.30      70.42
2021-05-01  57719     -0.02      69.01
2021-07-01  35030     -0.39      42.10
2021-08-01  41510      0.18      49.68
2021-09-01  47129      0.14      56.63
2021-10-01  43824     -0.07      52.67
2021-11-01  61310      0.40      73.73
2021-12-01  56891     -0.07      68.57
2022-03-01  43187     -0.24      52.11
2022-04-01  45529      0.05      54.72
2022-08-01  23303     -0.49      27.91
2022-10-01  19422     -0.17      23.16
2022-11-01  20496      0.06      24.55
2023-01-01  16537     -0.19      19.89
2023-02-01  23124      0.40      27.84
2023-03-01  23130      0.00      27.84
2023-04-01  28473      0.23      34.25
2023-05-01  29252      0.03      35.27
2023-06-01  27216     -0.07      32.81
2023-07-01  30472      0.12      36.74
2023-08-01  29232     -0.04      35.27
2023-09-01  25938     -0.11      31.39
2023-10-01  26962      0.04      32.65
2023-11-01  34648      0.29      42.12
2023-12-01  37712      0.09      45.91
2024-01-01  42272      0.12      51.42
2024-02-01  42580      0.01      51.93
2024-03-01  61157      0.44      74.78

In [ ]:
peores

             Open  retornos  ganancias
Date
2014-03-01    573     -0.39   0.713700
2018-12-01   4038     -0.37   4.948627
2022-07-01  19926     -0.37  24.076322
2021-06-01  37294     -0.35  45.280700
2018-04-01   6939     -0.33   8.633020
2015-02-01    218     -0.31   0.273803
2018-02-01  10266     -0.26  12.757529
2020-04-01   6412     -0.25   7.660960
2014-04-01    444     -0.23   0.549549
2014-10-01    388     -0.19   0.483425
2015-09-01    229     -0.19   0.285434
2018-06-01   7502     -0.19   9.300353
2022-01-01  46217     -0.19  56.157374
2014-09-01    481     -0.18   0.596820
2019-12-01   7546     -0.18   9.088947
2022-02-01  38475     -0.17  46.610621
2022-05-01  37642     -0.17  45.495695
2022-06-01  31793     -0.16  38.216383
2022-12-01  17163     -0.16  20.923355
2015-01-01    318     -0.15   0.396817
2018-07-01   6398     -0.15   7.905300
2016-02-01    369     -0.14   0.464173
2019-10-01   8285     -0.14  10.076438
2022-09-01  20049     -0.14  24.225595
2014-11-01    337     -0.13   0.420579

In [ ]:
# Crear un DataFrame vacío para almacenar los peores retornos de cada mes
peores_meses = pd.DataFrame(columns=btc_mes.columns)

# Iterar sobre cada mes
for fecha_inicio, datos_mes in btc_mes.groupby(pd.Grouper(freq='M')):
    # Encontrar los 20 peores retornos para este mes
    peores_mes_actual = datos_mes.nsmallest(20, 'retornos', keep='all')
    # Agregar los peores retornos de este mes al DataFrame de peores_meses
    peores_meses = pd.concat([peores_meses, peores_mes_actual])

# Ver los peores retornos para cada mes
print(peores_meses)

             Open  retornos  ganancias
2014-01-01    805       NaN        NaN
2014-02-01    938      0.17   1.170000
2014-03-01    573     -0.39   0.713700
2014-04-01    444     -0.23   0.549549
2014-05-01    445      0.00   0.549549
2014-06-01    627      0.41   0.774864
2014-07-01    635      0.01   0.782613
2014-08-01    589     -0.07   0.727830
2014-09-01    481     -0.18   0.596820
2014-10-01    388     -0.19   0.483425
2014-11-01    337     -0.13   0.420579
2014-12-01    374      0.11   0.466843
2015-01-01    318     -0.15   0.396817
2015-02-01    218     -0.31   0.273803
2015-03-01    254      0.17   0.320350
2015-04-01    244     -0.04   0.307536
2015-05-01    235     -0.04   0.295235
2015-06-01    229     -0.03   0.286378
2015-07-01    264      0.15   0.329334
2015-08-01    283      0.07   0.352388
2015-09-01    229     -0.19   0.285434
2015-10-01    235      0.03   0.293997
2015-11-01    311      0.32   0.388076
2015-12-01    378      0.22   0.473453
2016-01-01    430      0.14   0.539736
2016-02-01    369     -0.14   0.464173
2016-03-01    436      0.18   0.547724
2016-04-01    415     -0.05   0.520338
2016-05-01    448      0.08   0.561965
2016-06-01    528      0.18   0.663119
2016-07-01    670      0.27   0.842161
2016-08-01    621     -0.07   0.783210
2016-09-01    573     -0.08   0.720553
2016-10-01    608      0.06   0.763786
2016-11-01    698      0.15   0.878354
2016-12-01    742      0.06   0.931055
2017-01-01    963      0.30   1.210372
2017-02-01    965      0.00   1.210372
2017-03-01   1189      0.23   1.488757
2017-04-01   1079     -0.09   1.354769
2017-05-01   1351      0.25   1.693461
2017-06-01   2303      0.70   2.878884
2017-07-01   2480      0.08   3.109195
2017-08-01   2883      0.16   3.606666
2017-09-01   4735      0.64   5.914932
2017-10-01   4360     -0.08   5.441738
2017-11-01   6449      0.48   8.053772
2017-12-01   9947      0.54  12.402809
2018-01-01  13850      0.39  17.239904
2018-02-01  10266     -0.26  12.757529
2018-03-01  10335      0.01  12.885105
2018-04-01   6939     -0.33   8.633020
2018-05-01   9245      0.33  11.481917
2018-06-01   7502     -0.19   9.300353
2018-07-01   6398     -0.15   7.905300
2018-08-01   7728      0.21   9.565413
2018-09-01   7032     -0.09   8.704525
2018-10-01   6635     -0.06   8.182254
2018-11-01   6365     -0.04   7.854964
2018-12-01   4038     -0.37   4.948627
2019-01-01   3709     -0.08   4.552737
2019-02-01   3437     -0.07   4.234045
2019-03-01   3816      0.11   4.699790
2019-04-01   4102      0.07   5.028776
2019-05-01   5321      0.30   6.537408
2019-06-01   8556      0.61  10.525228
2019-07-01  10821      0.26  13.261787
2019-08-01  10081     -0.07  12.333462
2019-09-01   9594     -0.05  11.716789
2019-10-01   8285     -0.14  10.076438
2019-11-01   9153      0.10  11.084082
2019-12-01   7546     -0.18   9.088947
2020-01-01   7196     -0.05   8.634500
2020-02-01   9349      0.30  11.224850
2020-03-01   8543     -0.09  10.214613
2020-04-01   6412     -0.25   7.660960
2020-05-01   8628      0.35  10.342296
2020-06-01   9454      0.10  11.376526
2020-07-01   9135     -0.03  11.035230
2020-08-01  11333      0.24  13.683685
2020-09-01  11644      0.03  14.094196
2020-10-01  10776     -0.07  13.107602
2020-11-01  13795      0.28  16.777730
2020-12-01  19697      0.43  23.992155
2021-01-01  28951      0.47  35.268467
2021-02-01  33106      0.14  40.206053
2021-03-01  45160      0.36  54.680231
2021-04-01  58763      0.30  71.084301
2021-05-01  57719     -0.02  69.662615
2021-06-01  37294     -0.35  45.280700
2021-07-01  35030     -0.06  42.563858
2021-08-01  41510      0.18  50.225352
2021-09-01  47129      0.14  57.256901
2021-10-01  43824     -0.07  53.248918
2021-11-01  61310      0.40  74.548486
2021-12-01  56891     -0.07  69.330092
2022-01-01  46217     -0.19  56.157374
2022-02-01  38475     -0.17  46.610621
2022-03-01  43187      0.12  52.203895
2022-04-01  45529      0.05  54.814090
2022-05-01  37642     -0.17  45.495695
2022-06-01  31793     -0.16  38.216383
2022-07-01  19926     -0.37  24.076322
2022-08-01  23303      0.17  28.169296
2022-09-01  20049     -0.14  24.225595
2022-10-01  19422     -0.03  23.498827
2022-11-01  20496      0.06  24.908757
2022-12-01  17163     -0.16  20.923355
2023-01-01  16537     -0.04  20.086421
2023-02-01  23124      0.40  28.120990
2023-03-01  23130      0.00  28.120990
2023-04-01  28473      0.23  34.588817
2023-05-01  29252      0.03  35.626482
2023-06-01  27216     -0.07  33.132628
2023-07-01  30472      0.12  37.108544
2023-08-01  29232     -0.04  35.624202
2023-09-01  25938     -0.11  31.705540
2023-10-01  26962      0.04  32.973761
2023-11-01  34648      0.29  42.536152
2023-12-01  37712      0.09  46.364406
2024-01-01  42272      0.12  51.928134
2024-02-01  42580      0.01  52.447416
2024-03-01  61157      0.44  75.524279

C:\Users\pobla\AppData\Local\Temp\ipykernel_456\74438097.py:5: FutureWarning:

'M' is deprecated and will be removed in a future version, please use 'ME' instead.

C:\Users\pobla\AppData\Local\Temp\ipykernel_456\74438097.py:9: FutureWarning:

The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.

C:\Users\pobla\AppData\Local\Temp\ipykernel_456\74438097.py:9: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.